### ISSUE TITLE
经过测试，还是重复

### ISSUE THREAD

**Issue by yuxueliang** [mschuler/UniqueIdGenerator#5]
var blockingCollection = new BlockingCollection<long>();
            List<Task> tasks = new List<Task>();
            for (int i = 0; i < 100; i++)
            {
                var task = Task.Run(() =>
                {

                    for (int j = 0; j < 10000; j++)
                    {

                        blockingCollection.Add(new Generator(1, DateTime.MinValue).Next());
                    }
                });

                tasks.Add(task);
            }

            Task.WaitAll(tasks.ToArray());

            Console.WriteLine(blockingCollection.Distinct().Count());

            Console.ReadKey();

**Comment by hanslai** [comment]
I guess, I will translate the issue title.  What @yuxueliang  said was: “After some test, it will still generated duplicated Ids.”

**Comment by jhabjan** [comment]
There is nothing wrong with this library and it works as expected without creating duplicates. Issue here is your poor implementation. Why would you create new instance of Generator for every iteration? With example you provided result is as expected.

**Comment by mschuler** [comment]
As @jhabjan said, you must not create new instances of `Generator` with the same Instance ID (in your case 1). If you create multiple generators, use unique instance id's.
