### ISSUE TITLE
Duplicate ids in multi-threaded 

### ISSUE THREAD

**Issue by mustafamagdy** [mschuler/UniqueIdGenerator#7]
I tried the generator (1 generator) for 1000 times for 3 threads, and it gives me duplicated values

```
// Create a new instance of the generator
      Generator gen1 = new Generator(128, new DateTime(2019, 05, 1));

      int max = 1000;
      List<string> ids = new List<string>();

      for (int i = 0; i < max; i++) {
        ids.Add(gen1.Next());
      }

      Task t1 = Task.Factory.StartNew(() => {
        for (int i = 0; i < max; i++) {
          ids.Add(gen1.Next());
        }
      });

      Task t2 = Task.Factory.StartNew(() => {
        for (int i = 0; i < max; i++) {
          ids.Add(gen1.Next());
        }
      });

      Task.WaitAll(t1, t2);

      var grouped = (from i in ids group i by i into g select new { Id = g.Key, Count = g.Count() });

      var duplicated = grouped.Count(g => g.Count > 1);
      Console.WriteLine("duplicated ids  " + duplicated);
      //Failed
      Debug.Assert(0 == duplicated);
```

**Comment by karolswdev** [comment]
Hi @mschuler, would you like the community to solve this issue?

**Comment by mschuler** [comment]
This is by design. You have to create a generator for each thread / application.
What's the reason for creating multiple generatores? If you have a distributed microservice application, you have one generator with unique thread-id per service instance. If your application is not distributed, do you really need multiple generators?

**Comment by karolswdev** [comment]
Thanks @mschuler for your prompt response. Makes sense.

**Comment by flyingfive** [comment]
> List<string> ids = new List<string>();

@mschuler 
I have tried this issue, and i think duplicate ids is because of List are not thread safe, use ConcurrentDictionary instead List, there are no duplicate ids.
